### PR TITLE
fix: initialise indent_text at given index when inserting a new row

### LINKED ISSUE #11: Error adding new row at bottom of table
Cannot add a new row at the bottom of a table

create a new table (alt-t)
nav to last row
create a new row at bottom of table (alt-j)
error: indent_text is nil

### PR DESCRIPTION
**Pull request by clemdavies**
fix for issue: Error adding new row at bottom of table #11

Closes #11

### CODE REVIEW

File: lua/table-nvim/md_table.lua [hunk 1]
```diff
@@ -291,6 +291,7 @@ function MdTable:insert_row_at(index)
   row[col_count] = cell_x
 
   table.insert(self.rows, index, row)
+  table.insert(self.indent_text, index, self.indent_text[index] or string.rep(' ', self.indent))
```
Comment (SCJangra) [inline lua/table-nvim/md_table.lua]: Hi @clemdavies, thanks for the PR.

This looks good overall, but there’s a small issue: when inserting rows at the bottom of the table, the code will always use **spaces** as the indentation, even when the existing rows use a different indent style. For example, adding a new row to a table nested inside blockquotes causes the `>` prefix to be omitted, resulting in something like:

```markdown
> | Column1 | Column2 |
> | ------- | ------- |
> | x       | x       |
> | x       | x       |
  | x       | x       |
```

Using the indentation from the previous row should solve this. In other words, `self.indent_text[index]` should be replaced with `self.indent_text[index - 1]`.

**Review by SCJangra — CHANGES_REQUESTED** [review]
